PJPWEJockey/PJPWEJockey (1)/PJPWEJockey/src/java/pj/pwe/jsf/beans/Estacionamento.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pj.pwe.jsf.beans;


import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * @author HPmaster
 * 
 */
@RequestScoped 
@Entity
public class Estacionamento {
    
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    //anotação acima indica que o campo será gerado automaticamente pelo BD
    @Column(name="id")
    private int id;
    
    @Column(name="numeroVaga")
    private int numeroVaga;
    @Column(name="valor")
    private float valor;
   
     
     
     public Estacionamento(){
        
    }

    public int getNumeroVaga() {
        return numeroVaga;
    }

    public void setNumeroVaga(int numeroVaga) {
        this.numeroVaga = numeroVaga;
    }

   

    public float getValorVaga() {
        return valor;
    }

    public void setValorVaga(float valor) {
        this.valor = valor;
    }
    

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }


   
}

PJPWEJockey/PJPWEJockey (1)/PJPWEJockey/src/java/pj/pwe/jsf/controllers/QuartoController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pj.pwe.jsf.controllers;

import java.sql.SQLException;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import pj.pwe.jsf.beans.Quarto;
import pj.pwe.jsf.daos.QuartoDAO;
import pj.pwe.jsf.repository.QuartoRepositoryImpl;

/**
 *
 * @author HPmaster
 */
@ManagedBean
public class QuartoController {
    
        private Quarto quarto;
        
        public QuartoController(){
           quarto = new Quarto();
        }
       
	public Quarto getCliente() {
		return quarto;
	}
        
	public void setQuarto(Quarto quarto) {
		this.quarto = quarto;
	}
 
	public String salvar(){
            new QuartoRepositoryImpl().adiciona(this.quarto);
            return "Salvo!";
	}
        
         public List<Quarto> listarTodos(){
            return new QuartoRepositoryImpl().listaTodos();
        }
         
        
    
        
}

PJPWEJockey/PJPWEJockey (1)/PJPWEJockey/web/CadastroCliente.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui" xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <h:outputScript library="js" name="Locale.js"/>
    
    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>Turfe - Gerenciador</title>
            </f:facet>
        </h:head>

        <h:body>

            <p:layout fullPage="true">
                <p:layoutUnit position="north" size="230" header="Cadastrar" style="background-color: black">
                    <f:view> Cadastre aqui os clientes:  <br /><br /></f:view>
                <f:view>
                    <h:form>
                         <h:outputText value="Nome Cliente: "/>
                        <h:inputText value="#{clienteController.cliente.nome}" id="nome" />

                        <h:outputText value="RG: "/>
                        <h:inputText value="#{clienteController.cliente.RG}" id="RG" />
                        
                         <h:outputText value="CPF "/>
                        <h:inputText value="#{clienteController.cliente.CPF}" id="CPF" />
                        
                        <h:outputText value="Telefone "/>
                        <h:inputText value="#{clienteController.cliente.telefone}" id="telefone" />

                        <h:outputText value="Placa do Carro "/>
                        <h:inputText value="#{clienteController.cliente.placaCarro}" id="placaCarro" />

                          <h:outputText value="email "/>
                        <h:inputText value="#{clienteController.cliente.email}" id="email" />
                        
                        <h:outputText value="senha "/>
                        <h:inputText value="#{clienteController.cliente.senha}" id="senha" />

                        <h:commandButton type="submit" value="Cadastrar cliente" action="#{clienteController.salvar}" />

                    </h:form> 
                 </f:view>  
                </p:layoutUnit>
                 <p:layoutUnit position="center" size ="150" style="color:red">
                     <center> <f:view>  <h:link outcome="index" value="Voltar" /></f:view>    </center>
                </p:layoutUnit>
            </p:layout>
        </h:body>

    </f:view>
</html>


PJPWEJockey/PJPWEJockey (1)/PJPWEJockey/web/CadastroEstacionamento.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui" xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <h:outputScript library="js" name="Locale.js"/>
    
    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>Turfe - Gerenciador</title>
            </f:facet>
        </h:head>

        <h:body>

            <p:layout fullPage="true">

                <p:layoutUnit position="north" size="230" header="Cadastrar" style="background-color: black">
                      <f:view> Cadastre a Vaga: <br /><br /></f:view>
                    <h:form>
                         <h:outputText value="Digite uma vaga de 1 a 180"/>
                        <h:inputText value="#{estacionamentoController.estacionamento.numeroVaga}" id="numeroVaga" />
                        <h:outputText value="Digite o valor da vaga"/>
                        <h:inputText value="#{estacionamentoController.estacionamento.valorVaga}" id="valorVaga" />


                        <h:commandButton type="submit" value="Cadastrar vaga" action="#{estacionamentoController.salvar}" />
                      
                    </h:form> 
                 
                </p:layoutUnit>


                <p:layoutUnit position="center" size="150"  style="background-color: black">
                    
                </p:layoutUnit>
                 <p:layoutUnit position="south" size ="150" style="color:red">
                     <center> <f:view>  <h:link outcome="index" value="Voltar" /></f:view>    </center>
                </p:layoutUnit>
            </p:layout>
        </h:body>

    </f:view>
</html>

PJPWEJockey/PJPWEJockey (1)/PJPWEJockey/web/CadastroFuncionario.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui" xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <h:outputScript library="js" name="Locale.js"/>
    
    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>Turfe - Gerenciador</title>
            </f:facet>
        </h:head>

        <h:body>

            <p:layout fullPage="true">

                <p:layoutUnit position="north" size="200" header="Cadastrar" style="background-color: black">
                       <f:view> Cadastre aqui os funcionários: <br /><br /></f:view>
                    <h:form>
                         <h:outputText value="Nome Funcionário "/>
                        <h:inputText value="#{funcionarioController.funcionario.nome}" id="nome" />

                        <h:outputText value="RG: "/>
                        <h:inputText value="#{funcionarioController.funcionario.RG}" id="RG" />
                        
                         <h:outputText value="CPF "/>
                        <h:inputText value="#{funcionarioController.funcionario.CPF}" id="CPF" />
                        
                        <h:outputText value="Telefone "/>
                        <h:inputText value="#{funcionarioController.funcionario.telefone}" id="telefone" />

                        <h:outputText value="Placa do Carro "/>
                        <h:inputText value="#{funcionarioController.funcionario.placaCarro}" id="placaCarro" />

                          <h:outputText value="email"/>
                        <h:inputText value="#{funcionarioController.funcionario.email}" id="email" />
                        
                        <h:outputText value="senha"/>
                        <h:inputText value="#{funcionarioController.funcionario.senha}" id="senha" />
                        
                        <h:outputText value="salario"/>
                        <h:inputText value="#{funcionarioController.funcionario.salario}" id="salario" />     
                        
                        <h:commandButton type="submit" value="Cadastrar cavalo" action="#{funcionarioController.salvar}" />
                    </h:form> 
                </p:layoutUnit>
                 <p:layoutUnit position="center" size ="150" style="color:red">
                     <center> <f:view>  <h:link outcome="index" value="Voltar" /></f:view>    </center>
                </p:layoutUnit>
            </p:layout>
        </h:body>

    </f:view>
</html>

PJPWEJockey/PJPWEJockey (1)/PJPWEJockey/web/CadastroProduto.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui" xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <h:outputScript library="js" name="Locale.js"/>
    
    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>Turfe - Gerenciador</title>
            </f:facet>
        </h:head>

        <h:body>

            <p:layout fullPage="true">

                <p:layoutUnit position="north" size="200" header="Cadastrar" style="background-color: black">
                       <f:view> Cadastre aqui os produtos: <br /><br /></f:view>
                    <h:form>
                         <h:outputText value="descricao "/>
                        <h:inputText value="#{produtoController.produto.descricao}" id="descricao" />

                        <h:outputText value="preco: "/>
                        <h:inputText value="#{produtoController.produto.preco}" id="produto" />
                        
                         
                             
                        
                        <h:commandButton type="submit" value="Cadastrar produto" action="#{produtoController.salvar}" />
                    </h:form> 
                </p:layoutUnit>
                 <p:layoutUnit position="center" size ="150" style="color:red">
                     <center> <f:view>  <h:link outcome="index" value="Voltar" /></f:view>    </center>
                </p:layoutUnit>
            </p:layout>
        </h:body>

    </f:view>
</html>

PJPWEJockey/PJPWEJockey (1)/PJPWEJockey/web/Listar.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    

    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>PrimeFaces</title>
            </f:facet>
        </h:head>

         <h:body>

            <p:layout fullPage="true">

                 <p:layoutUnit position="north" size="280" header="Listar Cavalos" style="background-color: black">
                    <h:form>
                        <p:dataList value="#{cavaloController.listarTodos()}" var="cavalo" type="unordered" itemType="none" paginator="true" rows="5" styleClass="paginated">
                              <h:outputText value="#{cavalo.nome}, #{cavalo.raca}" style="display:inline-block"/>
                        </p:dataList>
                      
                    </h:form> 
                </p:layoutUnit>


                <p:layoutUnit position="center" size="200" header="Listar Corredores" style="background-color: black">
                    <h:form>
                        <p:dataList value="#{corredorController.listarTodos()}"  var="corredor" type="unordered" itemType="none" paginator="true" rows="5" styleClass="paginated">
                            <h:outputText value="#{corredor.nome}, #{corredor.alcunha}" style="display:inline-block"/>
                        </p:dataList>                      
                    </h:form> 
                </p:layoutUnit>
                 <p:layoutUnit position="south" size ="100" style="color:red">
                     <center> <f:view>  <h:link outcome="index" value="Voltar" /></f:view>    </center>
                </p:layoutUnit>
                
            </p:layout>
            
        </h:body>
    </f:view>
     #{facadeTeste.implementFacade()}
</html>
        
        

PJPWEJockey/PJPWEJockey (1)/PJPWEJockey/web/hotel.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
             <p:layout fullPage="true">
                <p:layoutUnit position="north" size="230" header="Cadastrar" style="background-color: black">
                    <f:view> Cadastre aqui os clientes:  <br /><br /></f:view>
                <f:view>
                    <h:form>
                        <p:selectOneMenu id="console" value="#{hospedagemController.hospedagem.teste}" style="width:125px">
                            <f:selectItem itemLabel="Select One" itemValue="" />
                            <f:selectItem itemLabel="Normal" itemValue="normal" />
                            <f:selectItem itemLabel="Suíte" itemValue="suite" />
                        </p:selectOneMenu>

                        <h:outputText value="RG: "/>
                        <h:inputText value="#{hospedagemController.hospedagem.estacionamento}" id="estacionamento" />
 
                        <h:commandButton type="submit" value="Cadastrar cavalo" action="#{funcionarioController.salvar}" />
                    </h:form>
                        
                 </f:view>  
                </p:layoutUnit>
                 <p:layoutUnit position="center" size ="150" style="color:red">
                     <center> <f:view>  <h:link outcome="index" value="Voltar" /></f:view>    </center>
                </p:layoutUnit>
            </p:layout>
        

            
      
    </h:body>
</html>

PJPWEJockey/PJPWEJockey (1)/PJPWEJockey/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Bem vindo ao Hotel Estada Feliz!</title>
    </h:head><center>
        <h:body>

        <p:layout fullPage="true">
         <p:layoutUnit position="center">
             
            <h:outputText value="Faça Login no Hotel Estada Feliz!"/>
             
            <f:view>
                <br /><br />
                 <h:form>
            <p:messages id="messages" />
            <p:panelGrid columns="2">
                  <p:outputLabel for="email" value="Nome Usuário:" />
                  <p:inputText id="email" value="#{clienteController.cliente.email}" />
                   
                  <p:outputLabel for="senha" value="Senha:" />
                  <p:password id="senha" value="#{clienteController.cliente.senha}" />
                   
                  <p:commandButton value="Enviar" icon="ui-icon-star" action="#{clienteController.envia}" ajax="false">
                  </p:commandButton>
                  
                  <h:link outcome="CadastroCliente" value="Não possui login? Cadastre-se!" />
                  <h:link outcome="CadastroFuncionario" value="Funcionario!" />
  
            </p:panelGrid>
      </h:form>

             </f:view>
         </p:layoutUnit>
        </p:layout>
    </h:body></center>
</html>

PJPWEJockey/PJPWEJockey (1)/PJPWEJockey/web/welcomePrimefaces.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>PrimeFaces</title>
            </f:facet>
        </h:head>

        <h:body>

            <p:layout fullPage="true">

                <p:layoutUnit position="north" size="100" resizable="true" closable="true" collapsible="true">
                    Header
                </p:layoutUnit>

                <p:layoutUnit position="south" size="100" closable="true" collapsible="true">
                    Footer
                </p:layoutUnit>

                <p:layoutUnit position="west" size="175" header="Left" collapsible="true">
                    <p:menu>
                        <p:submenu label="Resources">
                            <p:menuitem value="Demo" url="http://www.primefaces.org/showcase-labs/ui/home.jsf" />
                            <p:menuitem value="Documentation" url="http://www.primefaces.org/documentation.html" />
                            <p:menuitem value="Forum" url="http://forum.primefaces.org/" />
                            <p:menuitem value="Themes" url="http://www.primefaces.org/themes.html" />

                        </p:submenu>

                    </p:menu>
                </p:layoutUnit>

                <p:layoutUnit position="center">
                    Welcome to PrimeFaces
                </p:layoutUnit>

            </p:layout>

        </h:body>

    </f:view>
</html>